name: Deploy static site to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate project structure
        run: |
          echo "Verificando que exista index.html"
          if [ ! -f index.html ]; then
            echo "❌ Error: index.html no existe en el directorio raíz"
            exit 1
          fi
          echo "✅ index.html encontrado. Continuando..."

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel --prod --token $VERCEL_TOKEN --confirm --cwd .
